version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=kaddem  # Nom de la base de donn√©es
    ports:
      - 3308:3308
    volumes:
      - db:/var/lib/mysql
  achat-backend:
    depends_on:
      - mysql
    build: ./
    image: farahhasnaoui-5twin5-g5-kaddem:latest 
    restart: unless-stopped
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysqldb:3308/kaddem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" :  "",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
       }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
 

volumes:
  db: